# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pr: none

pool:
    vmImage: ubuntu-latest

stages:
- stage: "Test"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
        npm run test
        npm run karma
      displayName: 'Test the branch'

- stage: "Build"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: ./common-templates/security-pre-checks.yml
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build for production artifact'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        targetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copy npm package'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: "release-drop"
      displayName: 'Publish artifacts'

    - template: ./common-templates/security-post-checks.yml